# Generated by Django 5.2.8 on 2025-11-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='examiner_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('testtaker', 'Test Taker'), ('examiner', 'Examiner')], default='testtaker', max_length=20),
        ),
    ]
