# Generated by Django 5.2.8 on 2025-11-29 14:12

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_photos/'),
        ),
    ]
